export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const TRANSFER_TRANSACTION = 'TRANSFER_TRANSACTION'
export const SET_PROGRESS_BAR = 'SET_PROGRESS_BAR'
export const SET_FORM_PROGRESS_BAR = 'SET_FORM_PROGRESS_BAR'
